### ISSUE TITLE
行号出现了错位的情况

### ISSUE THREAD

**Issue by lingwu05** [Xcnte/Code-Prettify-for-typecho#9]
![image](https://user-images.githubusercontent.com/70186447/218245449-89ce0dae-65be-42b1-b343-a903fd34304d.png)
typecho版本：1.20
主题：默认主题

**Comment by yejing06** [comment]
joe出现同样问题

**Comment by Rockytkg** [comment]
> joe出现同样问题



> ![image](https://user-images.githubusercontent.com/70186447/218245449-89ce0dae-65be-42b1-b343-a903fd34304d.png) typecho版本：1.20 主题：默认主题

这个插件作者只支持了Handsome主题，其他主题可能需要自己修改代码适配一下。

**Comment by keeleycenc** [comment]
把插件里的行号显示关掉，然后pjax回调函数改成：
```js
    if (typeof Prism !== 'undefined') {
      Prism.highlightAll(true,null);
    }
```

**Comment by zideliu** [comment]
CSS也要改，[参考博客](https://www.zhaoyingtian.com/archives/65.html)
```css
/*代码高亮激活*/
#post-content pre code {
    display:block;
    overflow-x:auto;
    position:relative;
    margin:0;
    padding-left:50px;
}
pre code {
    position:relative;
    display:block;
    overflow-x:auto;
    margin:4.4px 0.px .4px 1px;
    padding:0;
    max-height:500px;
    padding-left:3.5em
}
```
